name: Test, Build and Package

on: [push]

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]

    runs-on: ubuntu-latest

    env:
        SRCPATH: ${{ github.workspace }}/go/src/monitoring-agent

    steps:
      
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
            
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRCPATH }}

      - name: Run Tests
        run: |
          pushd ${{ env.SRCPATH }}
          GO111MODULE=on GOOS=$os GOARCH=$arch go get ./...
          GO111MODULE=on go test -cover ./...

  build-release:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [linux, windows, freebsd]
        arch: [386, amd64]

    runs-on: ubuntu-latest

    needs: test
    
    env:
        SRCPATH: ${{ github.workspace }}/go/src/monitoring-agent

    steps:
        
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
            
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRCPATH }}

      - name: Dependencies & Build
        run: |
          os=${{ matrix.os }}
          arch=${{ matrix.arch }}
          goversion=${{ matrix.go-version }}

          echo "Building $os-$arch-$goversion"
          
          suffix=$([ "$os" == "windows" ] && echo ".exe" || echo "")

          mkdir -p ./release/$os-$arch-Go${goversion}
          cp ${{ env.SRCPATH }}/configuration.json ${{ env.SRCPATH }}/LICENSE ${{ env.SRCPATH }}/server.crt ${{ env.SRCPATH }}/server.key ${{ env.SRCPATH }}/README.md ${{ env.SRCPATH }}/cacert.pem ./release/$os-$arch-Go${goversion}
          
          pushd ${{ env.SRCPATH }}
          
          GO111MODULE=on GOOS=$os GOARCH=$arch go get ./...
          GO111MODULE=on GOOS=$os GOARCH=$arch go build -o ${{ env.SRCPATH }}/monitoring-agent$suffix

          popd

          cp ${{ env.SRCPATH }}/monitoring-agent$suffix ./release/$os-$arch-Go${goversion}/monitoring-agent$suffix
      
      - name: upload builds
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{ steps.short-sha.outputs.sha }}-BIN"
          path: release/

  build-win-MSI-installer:
  
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [windows]
        arch: [386, amd64]
        
    runs-on: windows-latest
    
    needs: test
    
    env:
        SRCPATH: ${{ github.workspace }}/go/src/monitoring-agent

    steps:
        
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Install WIX Tool Set
        run: |
          Invoke-WebRequest -UseBasicParsing -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
          & ".\wix311.exe" "/q"
            
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRCPATH }}

      - name: Dependencies & Build
        run: |
          $os="${{ matrix.os }}"
          $arch="${{ matrix.arch }}"
          $goversion="${{ matrix.go-version }}"
          Write-Host "Building $os-$arch-$goversion"
          
          New-Item -Type Directory ./release/$os-$arch-Go${goversion}
          
          Set-Location -Path ${{ env.SRCPATH }}
          $env:GO111MODULE="on" 
          $env:GOOS="$os"
          $env:GOARCH=$arch
          go get ./...
          go build -o ${{ env.SRCPATH }}/monitoring-agent.exe
          
      - name: Create MSI Installer
        run: |
          $os="${{ matrix.os }}"
          $arch="${{ matrix.arch }}"
          $goversion="${{ matrix.go-version }}"
          
          $win_arch = "x64"
          if ($arch -eq "386") { $win_arch = "x86" }
          Write-Host "Building MSI Installer For $os-$arch-Go${goversion}"
          
          $firstCommitSha = "49cded61e36172578146ca1a7ae516540056d8b0"
          $lastCommitSha = ((Invoke-WebRequest -uri https://api.github.com/repos/infraweavers/monitoring-agent/git/refs/heads/master -UseBasicParsing).Content | ConvertFrom-Json).object.sha
          $response = Invoke-WebRequest -uri https://api.github.com/repos/infraweavers/monitoring-agent/compare/${firstCommitSha}...${lastCommitSha} -UseBasicParsing
          $msiRevisionNumber = ($response.Content | ConvertFrom-Json).total_commits
          Write-Host "MSI Revision Number is: ${msiRevisionNumber}"
          
          Push-Location -Path ${{ env.SRCPATH }}
          & 'C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe' .\monitoring-agent.wxs -arch $win_arch -dPlatform="$($win_arch)" -dRevisionNumber="$($msiRevisionNumber)" -dGitSha="${{ steps.short-sha.outputs.sha }}"
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" "./monitoring-agent.wixobj"
          Pop-Location
          
          Move-Item -Path ${{ env.SRCPATH }}/monitoring-agent.msi -Destination "./release/$os-$arch-Go${goversion}/monitoring-agent-$win_arch-Go${goversion}-${{ steps.short-sha.outputs.sha }}.msi"
      - name: upload MSI
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.os }}-${{ matrix.arch }}-Go${{ matrix.go-version }}-${{ steps.short-sha.outputs.sha }}-MSI"
          path: release/

  create-deb:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [linux]
        arch: [386, amd64]

    runs-on: ubuntu-latest
    needs: test
    env:
        SRCPATH: ${{ github.workspace }}/go/src/mama

    steps:

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.SRCPATH }}

      - name: Dependencies & Build
        run: |
          os=${{ matrix.os }}
          arch=${{ matrix.arch }}
          goversion=${{ matrix.go-version }}
          echo "Building $os-$arch-$goversion"
          
          suffix=$([ "$os" == "windows" ] && echo ".exe" || echo "")
          mkdir -p ./release/$os-$arch-$goversion
          cp ${{ env.SRCPATH }}/configuration.json ${{ env.SRCPATH }}/LICENSE ${{ env.SRCPATH }}/server.crt ${{ env.SRCPATH }}/server.key ${{ env.SRCPATH }}/README.md ${{ env.SRCPATH }}/cacert.pem ./release/$os-$arch-$goversion
          pushd ${{ env.SRCPATH }}
          
          GO111MODULE=on GOOS=$os GOARCH=$arch go get ./...
          GO111MODULE=on GOOS=$os GOARCH=$arch go build -o ${{ env.SRCPATH }}/monitoring-agent$suffix
          popd
          cp ${{ env.SRCPATH }}/monitoring-agent$suffix ./release/$os-$arch-$goversion/monitoring-agent$suffix

      - name: Create .deb
        run: |
          os=${{ matrix.os }}
          arch=${{ matrix.arch }}
          goversion=${{ matrix.go-version }}
          
          mkdir -p deb-package/etc/monitoring-agent deb-package/usr/bin deb-package/lib/systemd/system
          cp -r ${{ env.SRCPATH }}/DEBIAN ./deb-package
          cp ${{ env.SRCPATH }}/configuration.json ${{ env.SRCPATH }}/server.crt ${{ env.SRCPATH }}/server.key ${{ env.SRCPATH }}/cacert.pem ./deb-package/etc/monitoring-agent
          cp ./release/$os-$arch-$goversion/monitoring-agent deb-package/usr/bin
          cp ${{ env.SRCPATH }}/monitoring-agent.service deb-package/lib/systemd/system

          sed -i 's|"LogFilePath": "output.log",|"LogFilePath": "/var/log/monitoring-agent.log",|' deb-package/etc/monitoring-agent/configuration.json
          sed -i 's|Architecture: UPDATEME|Architecture: ${{ matrix.arch }}|' deb-package/DEBIAN/control
          
          chmod 600 deb-package/etc/monitoring-agent/*
          sudo chown -R root:root deb-package/
          sudo dpkg-deb --build ./deb-package ~/linux-$arch-go$goversion-monitoring-agent.deb

      - name: Upload .deb
        uses: actions/upload-artifact@v2
        with:
          name: "linux-${{ matrix.arch }}-go${{ matrix.go-version }}-monitoring-agent-${{ steps.short-sha.outputs.sha }}.deb"
          path: ~/linux-${{ matrix.arch }}-go${{ matrix.go-version }}-monitoring-agent.deb
